version: '2.1'
services:
  db:
    image: mongo
  web:
    build: .
    command: bundle exec puma -e docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:mongo
networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:3984:3989::/64
