version: '3'
services:
  db:
    image: mongo
  web:
    build: .
    command: bundle exec rails s -e docker -p 8000 -b '0.0.0.0'
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:mongo
