development:
  clients:
    default:
      database: mj_data_explorer_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: mj_data_explorer_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: mj_data_explorer_production
      hosts:
        - localhost:27017
      options:
  options:
staging:
  clients:
    default:
      database: ai_social_rails_staging
      hosts:
        - localhost:27017
      options:
  options:
