development:
  clients:
    default:
      database: ai_social_rails_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: ai_social_rails_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: ai_social_rails_production
      hosts:
        - localhost:27017
      options:
  options:
